name:  Issue - Alta Nuevo Cliente

on:
  issues:
    types: [opened, labeled]

jobs:
  triage_nuevo_cliente:
    # Se ejecuta solo si la etiqueta 'Cliente-Nuevo' est谩 presente
    if: |
      (github.event_name == 'labeled' && github.event.label.name == 'Cliente-Nuevo') || 
      (github.event_name == 'opened' && contains(github.event.issue.labels.*.name, 'Cliente-Nuevo'))
    
    runs-on: ubuntu-latest
    steps:
      - name:  Simular Reacci贸n - Asignaci贸n a Back-end
        run: |
          echo "========================================================================"
          echo "::notice file=PLANIFICACION.md,title=Asignaci贸n (Cliente Nuevo)::Se ha detectado una solicitud de Nuevo Cliente (Issue #${{ github.event.issue.number }})."
          echo "::warning title=ACCIN REQUERIDA (EQUIPO BACKEND)::Por favor, revisar el Issue, coordinar la creaci贸n del registro y la validaci贸n de datos. Asignar al Desarrollador Backend."
          echo "Issue Creado por: ${{ github.event.issue.user.login }}"
          echo "========================================================================"