name: - Alta Nuevo Cliente

on:
  workflow_dispatch:
    inputs:
      issue_label:
        description: 'Selecciona la etiqueta de la Issue a procesar'
        required: true
        type: choice
        default: 'Cliente-Nuevo'
        options:
        # Solo se ejecuta si coincide con esta etiqueta
        - 'Cliente-Nuevo'
        - 'Cliente-Existente' 
        - 'Consulta'
        - 'Mejora'
        - 'Bugfix'
        - 'Nueva-Funcion'

jobs:
  triage_nuevo_cliente:
    # Se ejecuta solo si la entrada del usuario es 'Cliente-Nuevo'
    if: github.event.inputs.issue_label == 'Cliente-Nuevo'
    
    runs-on: ubuntu-latest
    steps:
      - name:  Simular Reacci贸n - Asignaci贸n a Back-end
        run: |
          echo "========================================================================"
          echo "::notice file=PLANIFICACION.md,title=Asignaci贸n (Cliente Nuevo)::Se ha procesado manualmente una solicitud de Nuevo Cliente."
          echo "::warning title=ACCIN REQUERIDA (EQUIPO BACKEND)::Por favor, revisar el Issue, coordinar la creaci贸n del registro y la validaci贸n de datos. Asignar al Desarrollador Backend."
          echo "Etiqueta Seleccionada: ${{ github.event.inputs.issue_label }}"
          echo "========================================================================"