name: - Mejora a la Aplicaci贸n

on:
  workflow_dispatch:
    inputs:
      area_mejora:
        description: 'rea de la aplicaci贸n a mejorar'
        required: true

jobs:
  simular_proceso:
    runs-on: ubuntu-latest
    steps:
      - name:  Simular Reacci贸n - Evaluaci贸n de Impacto (Manual)
        run: |
          echo "========================================================================"
          echo "::notice file=PLANIFICACION.md,title=Asignaci贸n (Mejora App - Manual)::Se ha iniciado una solicitud de Mejora en el 谩rea: ${{ github.event.inputs.area_mejora }}."
          echo "::warning title=ACCIN REQUERIDA (ANALISTA)::Realizar una **Evaluaci贸n de Impacto** y priorizaci贸n de la mejora. Asignar al Analista de Negocio (BA)."
          echo "Disparado por: ${{ github.actor }}"
          echo "========================================================================"